### ISSUE TITLE
Hi! And what about  telemetry?

### ISSUE THREAD

**Issue by ComPilErr** [dmrlawson/raspberrypi-dshot#3]
Does it use a Dhot protocol to get some telemetry data?

**Comment by dmrlawson** [comment]
No, I've not even attempted that. I just wanted to get the motors running.

**Comment by ComPilErr** [comment]
Yeah, and it works pretty good, by the way.

**Comment by dmrlawson** [comment]
Good to hear!

**Comment by ComPilErr** [comment]
Is it necessary to use dshot.send() function for all four drives in a code? I've tried to use only one call for one drive only, but it works strange then)

**Comment by dmrlawson** [comment]
The library is very simple and just sends what you tell it to. So to drive four motors you need four send commands in Python, e.g. 

```
for _ in range(10000):
    dshot.send(48, 5)
    dshot.send(48, 7)
    dshot.send(48, 19)
    dshot.send(48, 20)
```
You could extend the library to do this in the C code which might work better

**Comment by ComPilErr** [comment]
Ok, yes, it works completely fine for four motors. 
But if i use only one motor and do something like this:

for _ in range(10000):
    dshot.send(48, 5)

for _ in range(10000):
    dshot.send(148, 5)

then it works strange...

So i thought, that it is optimized for four drive-only use :)

**Comment by dmrlawson** [comment]
Ah. It's not intentionally, but it might be that the gap between packets is too short. You could try putting `time.sleep(0.0001)` after the send

**Comment by ComPilErr** [comment]
Yeah. now it's good. 
Thank you very much 👍
